### ISSUE TITLE
Set HTTP version of App Service to HTTP/2

### ISSUE THREAD

**Issue by bb-froggy** [scepman/deploy#14]
And do some testing as to whether the most common clients can work with that setting.

**Comment by bb-froggy** [comment]
Only for Certificate Master.

This option does not work with incoming client certificates and therefore is unsuited for SCEPman.

**Comment by o-l-a-v** [comment]
Maybe add `"properties": {"siteConfig": {"http20Enabled": false}}` to SCEPman in [`appSvcDouble.json`](https://github.com/scepman/install/blob/master/nestedtemplates/appSvcDouble.json) then?

**Comment by bb-froggy** [comment]
Good idea to make this explict.
